"""Add invoice_path to Sale

Revision ID: 5bc8ecc64f5d
Revises: 77dd89a1b845
Create Date: 2025-02-14 09:46:45.699024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc8ecc64f5d'
down_revision = '77dd89a1b845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('invoice_path')

    # ### end Alembic commands ###
